Spring Boot SPA article
p2-inc/phasetwo-docs pull request #158
Opened 2024-05-12 07:41 UTC by rtufisi

2024-05-13 16:41 UTC, xgp requested changes
Looks great. A few edits but otherwise :+1:

2024-05-13 16:41 UTC, xgp commented on blog/2024-05-09-secure-spring-boot.mdx
> +title: Securing SPA Application with Spring Boot and Keycloak
Securing **a** SPA Application with Spring Boot and Keycloak

2024-05-13 16:41 UTC, xgp commented on blog/2024-05-09-secure-spring-boot.mdx
> +  [phase_two, tutorial, frameworks, spring-boot, authentication, authorization, sso]
`spring_boot` should be snake case.

2024-05-13 16:41 UTC, xgp commented on blog/2024-05-09-secure-spring-boot.mdx
> +[SpringBoot](https://spring.io/projects/spring-boot) is a open-source tool which uses Java based frameworks for building web applications.
"Java-based"

2024-05-13 16:41 UTC, xgp commented on blog/2024-05-09-secure-spring-boot.mdx
> +In this article we'll be using [Keycloak](https://www.keycloak.org/) to secure a SPA and access secured resources from Spring Boot Web application.
"from **a** Spring"

2024-05-13 16:41 UTC, xgp commented on blog/2024-05-09-secure-spring-boot.mdx
> +If you just want to skip to the code, visit the Phase Two [SpringBoot example](https://github.com/p2-inc/examples/tree/main/frameworks/spring-boot-keycloak). We are also building [Keycloak examples](
correct style is "Spring Boot" with a space.

2024-05-13 16:41 UTC, xgp commented on blog/2024-05-09-secure-spring-boot.mdx
> +In order to setup a SpringBoot project a JDK version must be chosen. To be inline with the latest changes from Keycloak 24, the Java 17 baseline will be used. Other JDk versions can also be used for
"JDK"

2024-05-13 16:41 UTC, xgp commented on blog/2024-05-09-secure-spring-boot.mdx
> +This configuration will make the SpringBoot to act as a OAuth2 Resource Server’s  with JWT authentication.
"make the SpringBoot act as a "

"an OAuth2 Resource Server"

2024-05-15 15:33 UTC, rtufisi commented
@xgp  all changes are performed. Please check again.

Please merge this when you and @jeffpatzer  manage to review this as well. https://github.com/p2-inc/examples/issues/6

Otherwise this section will be incomplete:

`:::info

If you just want to skip to the code, visit the Phase Two [Spring Boot example](https://github.com/p2-inc/examples/tree/main/frameworks/spring-boot-keycloak). We are also building [Keycloak examples](https://github.com/p2-inc/examples) for other frameworks.

:::

`

2024-05-15 15:49 UTC, xgp approved these changes
:+1:

2024-05-15 15:50 UTC, xgp commented
@pnzrr looks good from a spring boot, java and keycloak perspective. Please look at the angular part.

2024-05-20 18:51 UTC, pnzrr approved these changes

2024-05-20 18:51 UTC, merged